# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "base"
  config.vm.box = "centos/7"
  config.vm.define :docker do |docker_config|
    docker_config.vm.network :public_network,
    use_dhcp_assigned_default_route: true
  end
  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "2048"]
     vb.name = "DockerServer"
  end
end
